### ISSUE TITLE
No rule to make target '/usr/lib/libcurl.dylib'

### ISSUE THREAD

**Issue by cheershendtco** [Great-Hill-Corporation/ethslurp#87]
I follow video the make
and I got
 No rule to make target '/usr/lib/libcurl.dylib', needed by 'ethslurp'.  Stop.
How can I fix this 
thanks.

**Comment by tjayrush** [comment]
There's this section at the bottom of the README.md file. You need to download the 'curl' c++ library. These instructions are for Ubuntu and Mac.

**Building from source**

Currently we have no binaries to download, therefore you must build from source. We think there is only a single dependency in our code for the 'curl' libraries.

On Ubuntu you may run this command to get 'curl':

`apt-get install libcurl4-gnutls-dev`

On the Mac, this may be a good start:

`http://macappstore.org/curl/`

If you figure it out on Windows, please let me know and I will update the README

**Comment by tjayrush** [comment]
Here's some instructions for Windows: http://stackoverflow.com/questions/9507353/how-do-i-install-set-up-and-use-curl-on-a-windowse

**Comment by tjayrush** [comment]
What platform are you on?

=======================
Thomas Jay Rush
Great Hill Corporation
jrush@greathill.com
(610) 519-9413

**Comment by cheershendtco** [comment]
```
cheer@cheer-H97-D3H:~/mtest/ethslurp-master$ sudo apt-get install libcurl4-gnutls-dev
[sudo] password for cheer: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libcurl4-gnutls-dev is already the newest version (7.47.0-1ubuntu2.1).
The following packages were automatically installed and are no longer required:
  fonts-lato libbz2-dev libncurses5-dev libruby2.3 libtext-unidecode-perl libtinfo-dev libxml-libxml-perl libxml-namespacesupport-perl libxml-sax-base-perl libxml-sax-expat-perl libxml-sax-perl rake
  ruby ruby-did-you-mean ruby-minitest ruby-net-telnet ruby-power-assert ruby-test-unit ruby2.3 rubygems-integration tex-common texinfo
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.

ethslurp build started
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
make[2]: Entering directory '/home/cheer/mtest/ethslurp-master'
make[2]: *** No rule to make target '/usr/lib/libcurl.dylib', needed by 'ethslurp'.  Stop.
make[2]: Leaving directory '/home/cheer/mtest/ethslurp-master'
makefile:16: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/cheer/mtest/ethslurp-master'
ethslurp build started
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
make[1]: Entering directory '/home/cheer/mtest/ethslurp-master'
make[1]: *** No rule to make target '/usr/lib/libcurl.dylib', needed by 'ethslurp'.  Stop.
make[1]: Leaving directory '/home/cheer/mtest/ethslurp-master'
makefile:16: recipe for target 'all' failed
make: *** [all] Error 2

```

hihi thanks 
my os is ubuntu 16.04 lts

**Comment by tjayrush** [comment]
I made some changes that should fix it. To make this work, redownload the source, and edit the makefile to uncomment this line:

```
#curl_lib=/usr/lib/x86_64-linux-gnu/libcurl.so.4

```

If this doesn't work, then you have to find the location of the 'curl' library on your system. First do this command:

```
curl --version
```

If you get anything than a legit version message, you need to figure out the problem with your curl installation (I can't help you there). If 'curl' returns a version string, then it's properly installed. Next you need to find the curl libraries to link to. I found the location I mention above with this command:

```
find /usr/lib -name "*curl*"
```
This returned a long list of possible candidates. I simply picked the one that looked most likely (i.e. a library (.so on ubuntu) and the latest version 4.0 in my case.

Hope this helps.

Do me a favor and let me know either way. I also made some changes that I think should silence all warnings. If you see any warnings please let me know.

Thanks for the bug report.

**Comment by cheershendtco** [comment]
hihi it works!
how do I check in modern

like this one
https://testnet.etherscan.io/address/0x90EBf76aB1da4F64542be469C87759bF2a5C63C0
thanks

**Comment by tjayrush** [comment]
I'm glad to hear that. Do me a favor. I am going go to close this issue. Please open another issue for your next question. In this way, other people, when they have the same problem will be able to find it easily by the issue's title.

**Comment by AlexNewell** [comment]
Hi, may need to re-open this issue. I followed a similar path but the solution did not solve my problem. I can copy this over to a new issue though, just let me know.

- Running Ubuntu 16.04
- Downloaded from the GitHub page, followed Install.md directions
- First error produced the "No rule to make target '/usr/lib/libcurl.dylib', needed by 'ethslurp'." error reported above
- Uncommented “curl_lib=/usr/lib/x86_64-linux-gnu/libcurl.so.4” per instructions
- Restarted "make clean + make"
- New errors now produced
```
g++  -std=c++11 -Wall -O2 -DLINUX -I. -I./utillib -I./etherlib -I./daolib -c ethslurp.cpp -o objs/ethslurp.o
g++  -std=c++11 -Wall -O2 -DLINUX -I. -I./utillib -I./etherlib -I./daolib -c slurp_options.cpp -o objs/slurp_options.o
g++ -o ethslurp objs/ethslurp.o objs/slurp_options.o /usr/lib/x86_64-linux-gnu/libcurl.so.4  */*.a
utillib/utillib.a(curl_code.o): In function `fill_buffer(URL_FILE*, unsigned long)':
curl_code.cpp:(.text+0x18a): undefined reference to `curl_multi_timeout'
curl_code.cpp:(.text+0x1e1): undefined reference to `curl_multi_fdset'
(and other undefined references)
```

- "curl --version"  produces a correct version (curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3)
- Tried updating to a newer version... Detect new version via: find /usr/lib -name "*curl*", so replaced version in makefile to: curl_lib=/usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
- Other things... ensured libcurl was installed; tried both versions (apt-get install libcurl4-gnutls-dev; apt-get install libcurl4-openssl-dev)

Any ideas?

Thanks!

**Comment by tjayrush** [comment]
Quick question. When you do 'make clean + make’ is that two separate command or a single command line?

Did the output from the make after doing a make clean re-build the utillib and the etherlib folders or did you copy just the last few lines from the build?

I don’t see a re-make of the utillib folder (not that this would necessarily fix the problem), I just want to understand.

The ‘make clean’ should have caused the two subfolders to re-build.

=======================
Thomas Jay Rush
Great Hill Corporation
jrush@greathill.com
(610) 519-9413

**Comment by tjayrush** [comment]
Alex,

I really appreciate you spending the time. Sorry this is taking me so long to get your some data up there. Once you get ethslurp working on your machine, you should be able to download all but the internal transactions on your own.



=======================
Thomas Jay Rush
Great Hill Corporation
jrush@greathill.com
(610) 519-9413

**Comment by AlexNewell** [comment]
"Quick question. When you do 'make clean + make’ is that two separate command or a single command line?"
Two separate commands

"Did the output from the make after doing a make clean re-build the utillib and the etherlib folders or did you copy just the last few lines from the build?"

 Computer@Computer:~/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7$ make clean
make[1]: Entering directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/utillib'
make[1]: Leaving directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/utillib'
make[1]: Entering directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/etherlib'
make[1]: Leaving directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/etherlib'
make[1]: Entering directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/daolib'
make[1]: Leaving directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/daolib'
Computer@Computer:~/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7$ make
make[1]: Entering directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/utillib'
utillib.a build started
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
make[2]: Entering directory '/home/Computer/Projects/Blockchain/Great-Hill-Corporation-ethslurp-82e7cd7/utillib'_

**Comment by tjayrush** [comment]
That curl code has always been trouble for me. I'm greatly simplifying it I'll post it shortly. Try doing 'make cleanall' (one word) then 'make' in two separate commands. 

--------
Thomas Jay Rush
jrush@greathill.com

**Comment by AlexNewell** [comment]
Downloaded a fresh copy, performed a make cleanall, then a separate make.
No luck.

make[1]: Entering directory '(my
directories)/Great-Hill-Corporation-ethslurp-f22af7d'
g++  -std=c++11 -Wall -O2 -DLINUX -I. -I./utillib -I./etherlib -I./daolib
-c ethslurp.cpp -o objs/ethslurp.o
g++  -std=c++11 -Wall -O2 -DLINUX -I. -I./utillib -I./etherlib -I./daolib
-c slurp_options.cpp -o objs/slurp_options.o
make[1]: *** No rule to make target '/usr/lib/libcurl.dylib', needed by
'ethslurp'.  Stop.
make[1]: Leaving directory '(my
directories)/Great-Hill-Corporation-ethslurp-f22af7d'
makefile:20: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tjayrush** [comment]
Edit the makefile to use the Ubuntu location for curl. Sorry for the continued hassle.

There’s something called cmake that is supposed to solve this problem for multi-platform c++ builds, but I don’t know how to use that.

=======================
Thomas Jay Rush
Great Hill Corporation
jrush@greathill.com
(610) 519-9413
